
class page_subbasin_climate : public wxPanel {
	public:
		page_subbasin_climate
			(wxWindow *parent,
			const int id,
			class SubBasin *);

		void set_controls ();
		bool read_controls ();

		float_edit *edit_rainfalladjustment [12];
		float_edit *edit_temperatureadjustment [12];
		float_edit *edit_radiationadjustment [12];
		float_edit *edit_humidityadjustment [12];

	protected:
		class SubBasin *basin;

		DECLARE_EVENT_TABLE()
};

enum {
	EDIT_RAINFALLADJUSTMENT1 = 101,
	EDIT_TEMPERATUREADJUSTMENT1,
	EDIT_RADIATIONADJUSTMENT1,
	EDIT_HUMIDITYADJUSTMENT1,
	EDIT_RAINFALLADJUSTMENT2,
	EDIT_TEMPERATUREADJUSTMENT2,
	EDIT_RADIATIONADJUSTMENT2,
	EDIT_HUMIDITYADJUSTMENT2,
	EDIT_RAINFALLADJUSTMENT3,
	EDIT_TEMPERATUREADJUSTMENT3,
	EDIT_RADIATIONADJUSTMENT3,
	EDIT_HUMIDITYADJUSTMENT3,
	EDIT_RAINFALLADJUSTMENT4,
	EDIT_TEMPERATUREADJUSTMENT4,
	EDIT_RADIATIONADJUSTMENT4,
	EDIT_HUMIDITYADJUSTMENT4,
	EDIT_RAINFALLADJUSTMENT5,
	EDIT_TEMPERATUREADJUSTMENT5,
	EDIT_RADIATIONADJUSTMENT5,
	EDIT_HUMIDITYADJUSTMENT5,
	EDIT_RAINFALLADJUSTMENT6,
	EDIT_TEMPERATUREADJUSTMENT6,
	EDIT_RADIATIONADJUSTMENT6,
	EDIT_HUMIDITYADJUSTMENT6,
	EDIT_RAINFALLADJUSTMENT7,
	EDIT_TEMPERATUREADJUSTMENT7,
	EDIT_RADIATIONADJUSTMENT7,
	EDIT_HUMIDITYADJUSTMENT7,
	EDIT_RAINFALLADJUSTMENT8,
	EDIT_TEMPERATUREADJUSTMENT8,
	EDIT_RADIATIONADJUSTMENT8,
	EDIT_HUMIDITYADJUSTMENT8,
	EDIT_RAINFALLADJUSTMENT9,
	EDIT_TEMPERATUREADJUSTMENT9,
	EDIT_RADIATIONADJUSTMENT9,
	EDIT_HUMIDITYADJUSTMENT9,
	EDIT_RAINFALLADJUSTMENT10,
	EDIT_TEMPERATUREADJUSTMENT10,
	EDIT_RADIATIONADJUSTMENT10,
	EDIT_HUMIDITYADJUSTMENT10,
	EDIT_RAINFALLADJUSTMENT11,
	EDIT_TEMPERATUREADJUSTMENT11,
	EDIT_RADIATIONADJUSTMENT11,
	EDIT_HUMIDITYADJUSTMENT11,
	EDIT_RAINFALLADJUSTMENT12,
	EDIT_TEMPERATUREADJUSTMENT12,
	EDIT_RADIATIONADJUSTMENT12,
	EDIT_HUMIDITYADJUSTMENT12
};
